module.exports = {
    str: "en",
    catalog: "Catalog 🗂",
    main_menu: "Main menu",
    not_your: "This is not your contact",
    share_contact: "Share contact",
    share_phone: "Share you contact",
    write_name: "Write your name",
    savat: "Cart 🛒",
    aksiya: "Promotions 🎁",
    my_aks: "My promos 🛍",
    settings: "Settings ⚙️",
    change_lang: "Change lang 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    change_name: "Change name 👤",
    back: "Back ⬅️",
    name_changed: "Name changed: ",
    choose: "Choose from list",
    price: "Price: ",
    add_cart: "Add to cart",
    not_found: "Product not found",
    added: "Added to cart: ",
    show_cart: "Show cart",
    in_cart: "🛒 In cart: ",
    empty: "Empty",
    clear: "Clear 🔄",
    order: "Order ✅",
    sum: "Cost: ",
    deliver: "Where we need to deliver?",
    share_location: "Share location",
    deliver_time: "Your order will be delivered within 2 days",
    confirm: "Confirm ✅",
    confirmed: "Your order confirmed!",
    coming_soon: "Coming soon!",
    you_spend: "Your total orders: ",
    order_confirmed: "Your order is accepted.",
    no_cat: "No such category",
    mass: "Weight: ",
    soon: "Soon!",
    sum: " sum"
}