module.exports = {
    str: "uz",
    catalog: "Katalog 📚",
    main_menu: "Bosh menyu",
    not_your: "Bu sizning kontaktingiz emas",
    share_contact: "Kontaktni yuborish",
    share_phone: "Kontaktingizni ulashing",
    write_name: "Ismingizni kiriting",
    savat: "Savat 🛒",
    aksiya: "Aksiyalar 🎁",
    my_aks: "Mening aksiyalarim 🛍",
    settings: "Sozlamalar ⚙️",
    change_lang: "Tilni o'zgartirish 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    change_name: "Ismni o'zgartirish 👤",
    back: "Ortga ⬅️",
    name_changed: "Ism o'zgartirildi: ",
    choose: "Tanlang",
    price: "Narxi (UZS): ",
    add_cart: "Savatga qo'shish",
    not_found: "Mahsulot topilmadi",
    added: "Savatga qo'shildi: ",
    show_cart: "Savatga o'tish",
    in_cart: "🛒 Savatchada: ",
    empty: "Bo'sh",
    clear: "Tozalash 🔄",
    order: "Buyurtirish ✅",
    sum: "Jami: ",
    deliver: "Qayerga yetkazish kerak?",
    share_location: "Lokatsiya yuborish",
    deliver_time: "Sizning buyurtmangiz 2 kun ichida yetkazib beriladi",
    confirm: "Tasdiqlash ✅",
    coming_soon: "Tez orada!",
    you_spend: "Sizning buyurtmalaringiz: ",
    order_confirmed: "Sizning buyurtmangiz qabul qilindi.",
    no_cat: "Bunday tur mavjud emas",
    mass: "Og'irligi: ",
    soon: "Tez orada!"
}
// Indiyskiy cherniy chay