module.exports = {
    str: "uz",
    catalog: "Katalog 🗂",
    main_menu: "Bosh menyu",
    not_your: "Bu sizning kontaktingiz emas",
    share_contact: "Kontaktni yuborish",
    share_phone: "Kontaktingizni ulashing",
    write_name: "Ismingizni kiriting",
    savat: "Savat 🛒",
    aksiya: "Aksiyalar 🎁",
    my_aks: "Mening aksiyalarim 🛍",
    settings: "Sozlamalar ⚙️",
    change_lang: "Tilni o'zgartirish 🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    change_name: "Ismni o'zgartirish 👤",
    back: "Ortga ⬅️",
    name_changed: "Ism o'zgartirildi: ",
    choose: "Tanlang",
    price: "Narxi: ",
    add_cart: "Savatga qo'shish",
    not_found: "Mahsulot topilmadi",
    added: "Savatga qo'shildi: ",
    show_cart: "Savatga o'tish",
    in_cart: "🛒 Savatchada: ",
    empty: "Bo'sh",
    clear: "Tozalash 🔄",
    order: "Buyurtirish ✅",
    suma: "Jami: ",
    deliver: "Yetkazib berish joyini yozing yoki lokatsiya yuboring.",
    share_location: "Lokatsiya yuborish",
    deliver_time: "Buyurtmani tasdiqlang va operator siz bilan tez orada bog'lanadi.",
    confirm: "Tasdiqlash ✅",
    coming_soon: "Tez orada!",
    you_spend: "Sizning buyurtmalaringiz: ",
    order_confirmed: "Sizning buyurtmangiz qabul qilindi.",
    no_cat: "Bunday tur mavjud emas!",
    mass: "Og'irligi: ",
    soon: "Tez orada!",
    sum: " so'm",
    gram: "g.",
    location: "Lokatsiya: ",
    aksiya_str: "6 ta Famila Herbal mahsulotlarini sotib oling va uch xil Famila Hind qora choyidan 1 tasini oling!"
}